---
version: "v2"
branches:
  only:
    - master
    - develop
  exclude:
    - feature/*
pipeline:
  - name: test
    image: node:10
    script:
      - npm install
      - npm run test
  - name: build
    image: node:12
    script:
      - npm install
      - npm run build
